### ISSUE TITLE
Squeeze in Matlang

### ISSUE THREAD

**Issue by aminya** [StevenWhitaker/Utils.jl#1]
For my package [MatLang](https://github.com/juliamatlab/MatLang), I need to provide `squeeze` function which works similar to Matlab's squeeze function (intelligent `dropdims` that drops all the dimensions that are 1)
Which method does the thing that I want?

https://github.com/StevenWhitaker/Utils.jl/blob/495c91bf19a9334294acfdc4440283e431222c43/src/arrays.jl#L165

**Comment by StevenWhitaker** [comment]
For the record, it is not recommended to use such a squeeze function because it is not type-stable, i.e., the type of the result of `squeeze` depends on the value of the input, not just its type. So there will be a performance penalty for using it. Although, that might not matter for your application.

If you still really want that functionality, the `squeeze` function I wrote does that:
https://github.com/StevenWhitaker/Utils.jl/blob/495c91bf19a9334294acfdc4440283e431222c43/src/arrays.jl#L183

However, there is a type-stable way to squeeze a singleton dimension that results from applying some sort of reduction to an array. See my macro `@squeeze`:
https://github.com/StevenWhitaker/Utils.jl/blob/495c91bf19a9334294acfdc4440283e431222c43/src/arrays.jl#L217

See the docstring for example usages. Note that macros in Julia can also look like function calls, i.e., `@squeeze sum(x, dims = 1)` is the same as `@squeeze(sum(x, dims = 1))`. The functional way of calling macros is convenient/necessary when it is part of a bigger expression, e.g., `@squeeze(sum(x, dims = 1))' * y`.

**Comment by aminya** [comment]
I don't want to supply `dim` keyword. I need an intelligent function which drops the dimensions. 
In many cases, `dim` is not known by the user.
I added you as the co-author of the commit. Thank you!
https://github.com/juliamatlab/MatLang/commit/80a80f94e82cfc5d13c31c24663475deb45f7989
